
version: '3'
services:

  db:
    image: postgres:13-alpine
    hostname: postgres13
    restart: always
    container_name: postgres13eventbus

    volumes:
      - /var/lib/postgresql

    environment:
      POSTGRES_DB: event_store
      POSTGRES_USER: event
      POSTGRES_PASSWORD: cqrs
    ports:
      - "5432:5432"